@extends('layouts.app')

@section('content')
    <h1>About</h1>
    <p class="just">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, odit nostrum. Natus, odit reprehenderit! Omnis ad consequuntur ipsum officia cumque! Iste, molestias quidem laudantium autem dolorem cupiditate? Tempora voluptas rem aliquid in? Corrupti soluta nisi voluptate sequi porro quaerat veniam blanditiis dolores nulla nam consequatur vitae, laborum temporibus atque laudantium.
    </p>
    <p class="just">
        Lorem ipsum dolor sit amet,arum adipisci iure reprehenderit beatae natus sunt tempora ullam recusandae facere quas, eveniet error corrupti soluta, similique doloremque corporis velit maiores? Tenetur voluptatibus obcaecati reiciendis earum aliquid velit magnam tempore iusto! In quia et iste molestiae eligendi cupiditate, explicabo fugiat laboriosam! Tenetur nemo doloremque nulla ducimus rerum maiores quo adipisci dolore vero, sed saepe nam sit molestiae ut animi voluptatem distinctio non deleniti suscipit doloribus omnis! Repellat temporibus ut similique atque reprehenderit expedita animi esse vero corrupti. Labore amet nisi voluptates at. Earum molestiae, quo sit possimus quibusdam similique? Excepturi laudantium aliquam iste, repellat, ipsum earum repudiandae odio officiis iusto ducimus explicabo, quasi ad atque vitae neque. Molestiae adipisci soluta sunt. Sint, quos iste, nesciunt reiciendis maiores numquam maxime ipsum sequi omnis eos ratione consequuntur necessitatibus sit quae illo molestias odio error, aut quasi impedit similique fugiat officiis vero? Hic unde, quasi aspernatur porro ab nemo natus temporibus magni distinctio. Amet pariatur est, architecto nesciunt eaque error dicta aliquid facilis maxime ea, doloremque ducimus deserunt obcaecati eveniet sed id adipisci unde asperiores placeat officia. Doloremque exercitationem laborum, molestiae minus architecto inventore aperiam ipsum quis eos delectus perspiciatis, reiciendis recusandae. Laboriosam ut rem distinctio aliquid, voluptate ipsum. Illo illum officiis odio ad tempora eum voluptates reiciendis suscipit, culpa, asperiores libero magni error iusto id iste dolores ipsam?
    </p>
@endsection